// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const disabledError = new Error(
  "Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to a .env file."
);

type DisabledResult<T> = { data: T; error: Error | null; count?: number | null };

const makeQuery = <T,>(result: DisabledResult<T>) => {
  const promise = Promise.resolve(result);
  return {
    then: promise.then.bind(promise),
    catch: promise.catch.bind(promise),
    finally: promise.finally.bind(promise),
    limit: () => makeQuery(result),
    order: () => makeQuery(result),
    eq: () => makeQuery(result),
    maybeSingle: () => makeQuery({ data: null as T, error: null, count: null }),
  };
};

const createDisabledClient = () => ({
  from: () => ({
    select: () => makeQuery({ data: [] as unknown[], error: null, count: 0 }),
    insert: async () => ({ data: null, error: disabledError }),
    update: () => ({
      eq: async () => ({ data: null, error: disabledError }),
    }),
    delete: () => ({
      eq: async () => ({ data: null, error: disabledError }),
    }),
  }),
  auth: {
    onAuthStateChange: (callback: (event: string, session: { user: null } | null) => void) => {
      const subscription = { unsubscribe: () => {} };
      setTimeout(() => callback("SIGNED_OUT", null), 0);
      return { data: { subscription } };
    },
    getSession: async () => ({ data: { session: null } }),
    signInWithPassword: async () => ({ error: disabledError }),
    signUp: async () => ({ error: disabledError }),
    signOut: async () => ({ error: null }),
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const disabledClient = createDisabledClient() as unknown as ReturnType<typeof createClient<Database>>;

export const supabase = hasSupabaseEnv
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : disabledClient;

export const isSupabaseConfigured = hasSupabaseEnv;
